name: AI Code Check

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  ai-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      
    - name: AI Citric-Sheep Watchdog
      uses: Citric-Sheep/ai-watchdog@v0.2.3
      with:
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
